figure('rend','painters','pos',[135 10 1000 650])

%% title
Title = uicontrol('Style','text',...
                  'Position', [250, 580, 500, 60],...
                  'String', 'Handover Simulator',...
                  'FontSize', 50);

%% handover policy
handover_policy_txt = uicontrol('Style','text', ...
                                'Position',[20 460 120 22],...
                                'String','Handover Policy',...
                                'FontSize', 16);

handover_policy_popup = uicontrol('Style', 'popup',...
                                  'String', {'Lazy','Eager','Threshold'},...
                                  'Position', [150 460 120 25],...
                                  'FontSize', 16, ...
                                  'Callback', @setmap); 

%% Path-Loss Model
path_loss_txt = uicontrol('Style','text', ...
                          'Position',[20 420 124 22],...
                          'String','Path-Loss Model',...
                          'FontSize', 16);
                   
path_loss_popup = uicontrol('Style', 'popup',...
                            'String', {'Smooth Transition','Two Ray Ground','COST 231'},...
                            'Position', [150 420 120 25],...
                            'FontSize', 16, ...
                            'Callback', @setmap);
                        
%% MS number / cell 
MS_num_txt = uicontrol('Style','text', ...
                       'Position',[20 380 120 22],...
                       'String','MS number/cell',...
                       'FontSize', 16);
                   
MS_num_sld = uicontrol('Style', 'slider',...
                       'Min',1,'Max',50,'Value',41,...
                       'Position', [156 375 108 20],...
                       'Callback', @surfzlim); 

%% Simulation Time
time_txt = uicontrol('Style','text', ...
                     'Position',[20 340 120 22],...
                     'String','Simulation Time',...
                     'FontSize', 16);
                 
time_sld = uicontrol('Style', 'slider',...
                     'Min',1,'Max',50,'Value',41,...
                     'Position', [156 335 108 20],...
                     'Callback', @surfzlim); 
             
%% Bandwidth
bandwidth_txt = uicontrol('Style','text', ...
                          'Position',[20 300 120 22],...
                          'String','Bandwidth',...
                          'FontSize', 16);

bandwidth_sld = uicontrol('Style', 'slider',...
                          'Min',1,'Max',50,'Value',41,...
                          'Position', [156 295 108 20],...
                          'Callback', @surfzlim);
                      
%% Temperature                      
temperature_txt = uicontrol('Style','text', ...
                            'Position',[20 260 120 22],...
                            'String','Temperature',...
                            'FontSize', 16);
                        
temperature_sld = uicontrol('Style', 'slider',...
                            'Min',1,'Max',50,'Value',41,...
                            'Position', [156 255 108 20],...
                            'Callback', @surfzlim);
                        
%% MS power                        
MS_power_txt = uicontrol('Style','text', ...
                         'Position',[20 220 120 22],...
                         'String','MS power',...
                         'FontSize', 16);

MS_power_sld = uicontrol('Style', 'slider',...
                         'Min',1,'Max',50,'Value',41,...
                         'Position', [156 215 108 20],...
                         'Callback', @surfzlim);                     

%% BS power                        
BS_power_txt = uicontrol('Style','text', ...
                         'Position',[20 180 120 22],...
                         'String','BS power',...
                         'FontSize', 16);
                   
BS_power_sld = uicontrol('Style', 'slider',...
                         'Min',1,'Max',50,'Value',41,...
                         'Position', [156 175 108 20],...
                         'Callback', @surfzlim);                     
                       
%% MS gain                        
MS_gain_txt = uicontrol('Style','text', ...
                        'Position',[20 140 120 22],...
                        'String','MS gain',...
                        'FontSize', 16);
                    
MS_gain_sld = uicontrol('Style', 'slider',...
                        'Min',1,'Max',50,'Value',41,...
                        'Position', [156 135 108 20],...
                        'Callback', @surfzlim);  
                    
%% BS gain                    
BS_gain_txt = uicontrol('Style','text', ...
                          'Position',[20 100 120 22],...
                          'String','BS gain',...
                          'FontSize', 16);

BS_gain_sld = uicontrol('Style', 'slider',...
                        'Min',1,'Max',50,'Value',41,...
                        'Position', [156 95 108 20],...
                        'Callback', @surfzlim);                        

%% MS height                      
MS_height_var_txt = uicontrol('Style','text', ...
                          'Position',[20 60 120 22],...
                          'String','MS height var',...
                          'FontSize', 16);
                      
MS_height_var_sld = uicontrol('Style', 'slider',...
                              'Min',1,'Max',50,'Value',41,...
                              'Position', [156 55 108 20],...
                              'Callback', @surfzlim);  
                      
%% BS height                      
BS_height_var_txt = uicontrol('Style','text', ...
                              'Position',[20 20 120 22],...
                              'String','BS height var',...
                              'FontSize', 16);
                      
BS_height_var_sld = uicontrol('Style', 'slider',...
                              'Min',1,'Max',50,'Value',41,...
                              'Position', [156 15 108 20],...
                              'Callback', @surfzlim);                       